
class LockProtocol(Protocol):
    def acquire(self, blocking: bool = True, timeout: float = -1) -> bool: ...
    def release(self) -> None: ...
    def locked(self) -> bool: ...


class QueueProtocol(Protocol):
    def put(self, item: Any) -> None: ...
    def get_nowait(self) -> Any: ...
    def task_done(self) -> None: ...


class ValueProtocol(Protocol):
    @property
    def value(self) -> bool: ...
    @value.setter
    def value(self) -> None: ...


class PlateType(TypedDict):
    queue: QueueProtocol
    locks: list[LockProtocol]
    stop: ValueProtocol
